openapi: 3.0.0
servers:
  - description: Production server
    url: https://smashbros-unofficial-api.vercel.app/api/v1
  - description: Development server
    url: http://localhost:3000/api/v1
info:
  description: Unofficial API for Super Smash Bros
  version: "1.0.0"
  title: Super Smash Bros
  contact:
    name: Leonardo Cabeza
    url: https://github.com/leocabeza/smashbros-unofficial-api
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: developers
    description: Operations available to regular developers
paths:
  /ultimate/characters:
    get:
      parameters:
        - name: name
          in: query
          description: Name of the character to filter for
          schema:
            type: string
      tags:
        - developers
      summary: list all smash ultimate characters
      operationId: listUltimateCharacters
      description: |
        List all smash ultimate characters
      responses:
        '200':
          description: returns all smash ultimate characters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Character'
  /ultimate/characters/{name}:
    get:
      parameters:
        - name: name
          in: path
          description: Name of the character to fetch
          required: true
          schema:
            type: string
      tags:
        - developers
      summary: get a specific ultimate character
      operationId: getUltimateCharacter
      description: |
        Get an specific Ultimate character
      responses:
        '200':
          description: returns ultimate character
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Character'
        '400':
          description: no character with that name was found
          content:
            text/plain
components:
  schemas:
    Character:
      type: object
      properties:
        alsoAppearsIn:
          type: array
          items:
            type: string
            enum:
              - SSB
              - Melee
              - Brawl
              - SSBWU/3DS
        availability:
          type: string
          enum:
            - Starter
            - Unlockable
            - Downloadable
        images:
          $ref: '#/components/schemas/Images'
        name:
          type: string
        order:
          type: number
          format: int32
        series:
          $ref: '#/components/schemas/Series'
    Images:
      type: object
      properties:
        name:
          type: string
        portrait:
          type: string
    Series:
      type: object
      properties:
        icon:
          type: string
        name:
          type: string